# Generated by Django 2.0 on 2018-01-23 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default='no-slug', max_length=160)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('last_mod_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Title')),
                ('body', models.TextField()),
                ('pub_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Posted')], default='p', max_length=1)),
                ('comment_status',
                 models.CharField(choices=[('o', 'Turn on'), ('c', 'Shut down')], default='o', max_length=1)),
                ('type', models.CharField(choices=[('a', 'Article'), ('p', 'Page')], default='a', max_length=1)),
                ('views', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Articles',
                'verbose_name_plural': 'Articles',
                'ordering': ['-pub_time'],
                'get_latest_by': 'created_time',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default='no-slug', max_length=160)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('last_mod_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('parent_category',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                   to='blog.Category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('link', models.URLField()),
                ('sequence', models.IntegerField(unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('last_mod_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Links',
                'verbose_name_plural': 'Links',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='SideBar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('sequence', models.IntegerField(unique=True)),
                ('is_enable', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('last_mod_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SideBar',
                'verbose_name_plural': 'SideBar',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default='no-slug', max_length=160)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('last_mod_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Tags',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.Tag'),
        ),
    ]
